version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: teamup_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: minh11992200
      MONGO_INITDB_ROOT_PASSWORD: minh0192
      MONGO_INITDB_DATABASE: testteamup
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - teamup_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: teamup_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://minh11992200:minh0192@testteamup.sahvubu.mongodb.net/teamUp?retryWrites=true&w=majority&appName=testTeamUp
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - teamup_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: teamup_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - teamup_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
    driver: local

networks:
  teamup_network:
    driver: bridge 